spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:5CGj982XIr2jqZ2nJrIh_Lr8XgxzmmiU-tEQz3FVGbxzU-cb@7b2b8506-54e2-4354-84f6-078a964a2df3.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}